export const friendsActions = {
    SET_FRIENDS : 'FRIENDS.SET_FRIENDS',
    SET_PENDING_FRIEND_INVITATIONS: 'FRIENDS.SET_PENDING_FRIEND_INVITATIONS',
    SET_ONLINE_USERS: 'FRIENDS.SET_ONLINE_USERS'
}